version: '2'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true


  login-exercise-infra:
    silent: true
    desc: exercise-infra-eks-91ux1mGn
    cmds:
      - aws eks --region eu-west-1 update-kubeconfig --name exercise-infra-eks-91ux1mGn